"""add webhook and polling fields to feature model

Revision ID: 03bcf4cf0146
Revises: c818a695f8c0
Create Date: 2026-01-07 15:29:49.515880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03bcf4cf0146"
down_revision: Union[str, Sequence[str], None] = "c818a695f8c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "features", sa.Column("webhook_secret", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "features", sa.Column("webhook_received_at", sa.DateTime(), nullable=True)
    )
    op.add_column("features", sa.Column("last_polled_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("features", "last_polled_at")
    op.drop_column("features", "webhook_received_at")
    op.drop_column("features", "webhook_secret")
    # ### end Alembic commands ###
