"""add metadata to features and rename metadata in brainstorm sessions

Revision ID: 152c677cea8b
Revises: 72ea51ad773b
Create Date: 2026-01-10 15:19:02.258620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152c677cea8b'
down_revision: Union[str, Sequence[str], None] = '72ea51ad773b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'metadata')
    # ### end Alembic commands ###
