"""add ideas table

Revision ID: 3edb4986d634
Revises: 97b6106e549a
Create Date: 2026-01-08 18:17:24.779586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3edb4986d634"
down_revision: Union[str, Sequence[str], None] = "97b6106e549a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ideas",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "BACKLOG",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "IMPLEMENTED",
                name="ideastatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="ideapriority"),
            nullable=False,
        ),
        sa.Column("business_value", sa.Integer(), nullable=True),
        sa.Column("technical_complexity", sa.Integer(), nullable=True),
        sa.Column("estimated_effort", sa.String(length=100), nullable=True),
        sa.Column("market_fit_analysis", sa.Text(), nullable=True),
        sa.Column("risk_assessment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "business_value IS NULL OR (business_value >= 1 AND business_value <= 10)",
            name="check_business_value_range",
        ),
        sa.CheckConstraint(
            "technical_complexity IS NULL OR (technical_complexity >= 1 AND technical_complexity <= 10)",
            name="check_technical_complexity_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ideas")
    # ### end Alembic commands ###
