"""Add metadata field to brainstorm_sessions

Revision ID: 72ea51ad773b
Revises: 8dfc784b46c2
Create Date: 2026-01-10 15:17:18.565537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72ea51ad773b'
down_revision: Union[str, Sequence[str], None] = '8dfc784b46c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tool_configs', 'enabled_for_agent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tool_configs', 'allow_use',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tool_configs', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_tool_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_tool_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_types', 'avatar_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('agent_types', 'personality_traits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('agent_types', 'streaming_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_types', 'max_context_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agent_types', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('agent_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_types', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_types', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('agent_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('brainstorm_sessions', sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
    op.alter_column('tool_usage_audit', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tool_usage_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tools', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tools', 'is_dangerous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tools', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tools', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tools', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tools', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tools', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tools', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tools', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tools', 'is_dangerous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tools', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tool_usage_audit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tool_usage_audit', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('brainstorm_sessions', 'metadata')
    op.alter_column('agent_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_types', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('agent_types', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_types', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_types', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('agent_types', 'max_context_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_types', 'streaming_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_types', 'personality_traits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('agent_types', 'avatar_color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('agent_tool_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_tool_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_tool_configs', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_tool_configs', 'allow_use',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('agent_tool_configs', 'enabled_for_agent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
